apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object-detection-app
  template:
    metadata:
      labels:
        app: object-detection-app
    spec:
      containers:
      - name: object-detection-app
        image: 977098994448.dkr.ecr.eu-west-2.amazonaws.com/object-detection-app
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  selector:
    app: object-detection-app
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: object-detection-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: object-detection-app.lab.abdirahman-ismail.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: object-detection-service
            port:
              number: 3000

  tls:
  - hosts:
    - object-detection-app.lab.abdirahman-ismail.com
    secretName: wildcard-tls