apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: object-detection-app
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/ABDIRAHMAN-I/MLOPs-Project.git
    targetRevision: HEAD
    path: object-detection-config

  destination:
    server: https://kubernetes.default.svc
    namespace: object-detection-config

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true