prometheus:
  extraArgs:
  - --insecure
  service: 
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"  
    annotations:
      nginx.org/hsts: "false"
      cert-manager.io/cluster-issuer: letsencrypt-dns-issuer
    hosts:
    - prometheus.lab.abdirahman-ismail.com
    tls:
    - secretName: argocd-ingress-tls
      hosts:
      - prometheus.lab.abdirahman-ismail.com
      