apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab.abdirahman-ismail.com
spec:
  secretName: wildcard-tls 
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*lab.abdirahman-ismail.com'
