apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab.abdirahman-ismail.com
  namespace: prometheus
spec:
  secretName: wildcard-tls 
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.lab.abdirahman-ismail.com"
    - grafana.lab.abdirahman-ismail.com
    - prometheus.lab.abdirahman-ismail.com
